apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: identity
  name: identity
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      serviceAccountName: identity-serviceaccount
      containers:
      - name: identity
        image: identity:1.0.0