apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: identity 
  name: identity-service 
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: identity 
  type: ClusterIP
status:
  loadBalancer: {}