apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: medulla-ingress
  namespace: medulla-system
spec:
  rules:
  - http:
      paths:
      - path: /shell/*
        pathType: Prefix
        backend:
          service:
            name: shell-service
            port:
              number: 80
      - path: /identity/*
        pathType: Prefix
        backend:
          service:
            name: identity-service
            port:
              number: 80
      - path: /documentation/*
        pathType: Prefix
        backend:
          service:
            name: documentation-service
            port:
              number: 80