apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shell
  name: shell
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      serviceAccountName: shell-serviceaccount
      containers:
      - name: shell
        image: shell:1.0.0
